### ISSUE TITLE
useMultipleSelection example doesn't filter in typeahead correctly

### ISSUE THREAD

**Issue by TheSisb** [downshift-js/downshift-docs#19]
Example: https://www.downshift-js.com/use-multiple-selection/#usage-with-combobox

Steps:
1. Start typing in the typeahead for that example: 
![image](https://user-images.githubusercontent.com/1592327/186737111-b48a8464-87e2-49b8-99e5-53cc2c5e0a8e.png)
2. Type "The"
3. The menu list is blank, but should show "The Idiot" by Fyodor.

**Comment by TheSisb** [comment]
I believe the fix is in the books filter function, something like this:

```
return books.filter(function filterBook(book) {
      return (
        !selectedItems.includes(book) &&
        (book.title.toLowerCase().includes(lowerCasedInputValue) ||
        book.author.toLowerCase().includes(lowerCasedInputValue))
      )
    })
```

**Comment by silviuaavram** [comment]
Thanks for reporting this! Will get it fixed.
