### ISSUE TITLE
ToggleKeyDownEnter/ToggleKeyDownSpaceButton incorrect types?

### ISSUE THREAD

**Issue by grelas** [downshift-js/downshift-docs#34]
Copied over the example from the Usage with Select example from https://www.downshift-js.com/use-multiple-selection/#usage-with-select and getting the following type errors for `ToggleKeyDownEnter` and `ToggleKeyDownSpaceButton`:

```
onStateChange: ({type, selectedItem}) => {
  switch (type) {
    case useSelect.stateChangeTypes.ToggleKeyDownEnter:
    case useSelect.stateChangeTypes.ToggleKeyDownSpaceButton:
    case useSelect.stateChangeTypes.ItemClick:
      if (selectedItem) {
        addSelectedItem(selectedItem)
      }
      break
    default:
      break
  }
},
```

```
Property 'ToggleKeyDownEnter' does not exist on type '{ ToggleButtonClick: UseSelectStateChangeTypes.ToggleButtonClick; 
Property 'ToggleKeyDownSpaceButton' does not exist on type '{ ToggleButtonClick: UseSelectStateChangeTypes.ToggleButtonClick; 
```
<img width="612" alt="image" src="https://user-images.githubusercontent.com/993698/217549734-9ca83030-f81b-4c16-a002-9d7769d75a51.png">

Should they be updated to use `ToggleButtonKeyDownEnter` and `ToggleButtonKeyDownSpaceButton`?

**Comment by silviuaavram** [comment]
What version of Downshift you are using?
